openapi: 3.0.0
info:
  license:
    name: MIT
  title: cross-chain-hackathon api
  version: 1.0.0
servers:
- url: http://localhost:8080/api/
paths:
  /estates:
    get:
      operationId: getEstates
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Estate'
                type: array
          description: success to get all estates
      summary: get all estates
      tags:
      - estate
  /estate/{estateId}:
    get:
      operationId: getEstateById
      parameters:
      - description: query target estate id
        explode: false
        in: path
        name: estateId
        required: true
        schema:
          $ref: '#/components/schemas/estate_id'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetEstateOutput'
          description: success to get the target estate
      summary: get an estate and its trade data
      tags:
      - estate
  /users:
    get:
      operationId: getUsers
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/User'
                type: array
          description: success to get all users
      summary: get all users
      tags:
      - user
  /user/{id}:
    get:
      operationId: getUser
      parameters:
      - description: user id
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/user_id'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
          description: success to get an user info
      summary: get user information
      tags:
      - user
  /trade/{id}:
    delete:
      operationId: deleteTrade
      parameters:
      - description: trade id
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/trade_id'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trade'
          description: success to cancel
      summary: cancel a trade
      tags:
      - trade
  /trades:
    post:
      operationId: postTrade
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Trade'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Trade'
          description: success to post
      summary: post a new sell offer
      tags:
      - trade
  /trade/requests:
    post:
      operationId: postTradeRequest
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostTradeRequestInput'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeRequest'
          description: success to post
      summary: post a new trade request
      tags:
      - trade
  /trade/request/{id}:
    delete:
      operationId: deleteTradeRequest
      parameters:
      - description: trade request id
        explode: false
        in: path
        name: id
        required: true
        schema:
          $ref: '#/components/schemas/trade_request_id'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TradeRequest'
          description: success to cancel
      summary: cancel a trade request
      tags:
      - trade
  /tx/trade/request:
    get:
      parameters:
      - explode: true
        in: query
        name: tradeId
        required: true
        schema:
          $ref: '#/components/schemas/trade_id'
        style: form
      - explode: true
        in: query
        name: from
        required: true
        schema:
          $ref: '#/components/schemas/AccAddress'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrossTx'
          description: success to get a CrossTx
      summary: get a CrossTx to be signed
      tags:
      - tx
  /tx/dividend:
    get:
      parameters:
      - explode: true
        in: query
        name: estateId
        required: true
        schema:
          $ref: '#/components/schemas/estate_id'
        style: form
      - explode: true
        in: query
        name: perShare
        required: true
        schema:
          $ref: '#/components/schemas/dividend_per_share'
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CrossTx'
          description: success to get a CrossTx
      summary: get a CrossTx to be signed
      tags:
      - tx
components:
  schemas:
    user_id:
      example: alice
      type: string
    estate_id:
      example: 108000000000078c000000000000000000000000000000000000000000000839
      maxLength: 64
      minLength: 64
      type: string
    trade_id:
      description: generated by the API server
      example: 0
      format: int64
      minimum: 0
      type: integer
    trade_request_id:
      description: generated by the API server
      example: 0
      format: int64
      minimum: 0
      type: integer
    dividend_id:
      example: 0
      format: int64
      minimum: 0
      type: integer
    dividend_per_share:
      example: 200
      format: int64
      minimum: 0
      type: integer
    Trade:
      example:
        seller: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
        canceled: true
        estateId: 108000000000078c000000000000000000000000000000000000000000000839
        price: 500
        id: 0
        requests:
        - canceled: true
          crossTx:
            type: cosmos-sdk/StdTx
            value:
              msg:
              - type: cross/MsgInitiate
                value:
                  Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  Nonce: "0"
                  TimeoutHeight: "149"
                  ContractTransactions:
                  - signers:
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    ops:
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    contract: contract
                    source:
                      port: cross
                      channel: ibcconexfer
                  - signers:
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    ops:
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    contract: contract
                    source:
                      port: cross
                      channel: ibcconexfer
                  ChainID: ibc0
              - type: cross/MsgInitiate
                value:
                  Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  Nonce: "0"
                  TimeoutHeight: "149"
                  ContractTransactions:
                  - signers:
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    ops:
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    contract: contract
                    source:
                      port: cross
                      channel: ibcconexfer
                  - signers:
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    ops:
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    contract: contract
                    source:
                      port: cross
                      channel: ibcconexfer
                  ChainID: ibc0
              fee:
                amount:
                - amount: 0
                  denom: denom
                - amount: 0
                  denom: denom
                gas: "200000"
              memo: memo
              signatures:
              - signature: signature
                pub_key: pub_key
              - signature: signature
                pub_key: pub_key
          from: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          id: 0
          tradeId: 0
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - canceled: true
          crossTx:
            type: cosmos-sdk/StdTx
            value:
              msg:
              - type: cross/MsgInitiate
                value:
                  Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  Nonce: "0"
                  TimeoutHeight: "149"
                  ContractTransactions:
                  - signers:
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    ops:
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    contract: contract
                    source:
                      port: cross
                      channel: ibcconexfer
                  - signers:
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    ops:
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    contract: contract
                    source:
                      port: cross
                      channel: ibcconexfer
                  ChainID: ibc0
              - type: cross/MsgInitiate
                value:
                  Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  Nonce: "0"
                  TimeoutHeight: "149"
                  ContractTransactions:
                  - signers:
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    ops:
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    contract: contract
                    source:
                      port: cross
                      channel: ibcconexfer
                  - signers:
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    ops:
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    - type: store/lock/Write
                      value:
                        V: V
                        K: K
                    contract: contract
                    source:
                      port: cross
                      channel: ibcconexfer
                  ChainID: ibc0
              fee:
                amount:
                - amount: 0
                  denom: denom
                - amount: 0
                  denom: denom
                gas: "200000"
              memo: memo
              signatures:
              - signature: signature
                pub_key: pub_key
              - signature: signature
                pub_key: pub_key
          from: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          id: 0
          tradeId: 0
          updatedAt: 2000-01-23T04:56:07.000+00:00
        type: buy
        buyer: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          description: generated by the API server
          example: 0
          format: int64
          minimum: 0
          type: integer
        estateId:
          example: 108000000000078c000000000000000000000000000000000000000000000839
          maxLength: 64
          minLength: 64
          type: string
        price:
          example: 500
          format: int64
          minimum: 0
          type: integer
        buyer:
          example: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          type: string
        seller:
          example: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          type: string
        type:
          enum:
          - buy
          - sell
          type: string
        requests:
          items:
            $ref: '#/components/schemas/TradeRequest'
          type: array
        canceled:
          type: boolean
        updatedAt:
          format: date-time
          type: string
      required:
      - canceled
      - estateId
      - id
      - price
      - requests
      - seller
      - type
      - updatedAt
      type: object
    TradeRequest:
      example:
        canceled: true
        crossTx:
          type: cosmos-sdk/StdTx
          value:
            msg:
            - type: cross/MsgInitiate
              value:
                Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                Nonce: "0"
                TimeoutHeight: "149"
                ContractTransactions:
                - signers:
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  ops:
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  contract: contract
                  source:
                    port: cross
                    channel: ibcconexfer
                - signers:
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  ops:
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  contract: contract
                  source:
                    port: cross
                    channel: ibcconexfer
                ChainID: ibc0
            - type: cross/MsgInitiate
              value:
                Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                Nonce: "0"
                TimeoutHeight: "149"
                ContractTransactions:
                - signers:
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  ops:
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  contract: contract
                  source:
                    port: cross
                    channel: ibcconexfer
                - signers:
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  ops:
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  contract: contract
                  source:
                    port: cross
                    channel: ibcconexfer
                ChainID: ibc0
            fee:
              amount:
              - amount: 0
                denom: denom
              - amount: 0
                denom: denom
              gas: "200000"
            memo: memo
            signatures:
            - signature: signature
              pub_key: pub_key
            - signature: signature
              pub_key: pub_key
        from: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
        id: 0
        tradeId: 0
        updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        id:
          description: generated by the API server
          example: 0
          format: int64
          minimum: 0
          type: integer
        tradeId:
          description: generated by the API server
          example: 0
          format: int64
          minimum: 0
          type: integer
        from:
          example: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          type: string
        crossTx:
          $ref: '#/components/schemas/CrossTx'
        canceled:
          type: boolean
        updatedAt:
          format: date-time
          type: string
      required:
      - canceled
      - crossTx
      - from
      - id
      - tradeId
      - updatedAt
      type: object
    PostTradeRequestInput:
      example:
        crossTx:
          type: cosmos-sdk/StdTx
          value:
            msg:
            - type: cross/MsgInitiate
              value:
                Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                Nonce: "0"
                TimeoutHeight: "149"
                ContractTransactions:
                - signers:
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  ops:
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  contract: contract
                  source:
                    port: cross
                    channel: ibcconexfer
                - signers:
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  ops:
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  contract: contract
                  source:
                    port: cross
                    channel: ibcconexfer
                ChainID: ibc0
            - type: cross/MsgInitiate
              value:
                Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                Nonce: "0"
                TimeoutHeight: "149"
                ContractTransactions:
                - signers:
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  ops:
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  contract: contract
                  source:
                    port: cross
                    channel: ibcconexfer
                - signers:
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                  ops:
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  - type: store/lock/Write
                    value:
                      V: V
                      K: K
                  contract: contract
                  source:
                    port: cross
                    channel: ibcconexfer
                ChainID: ibc0
            fee:
              amount:
              - amount: 0
                denom: denom
              - amount: 0
                denom: denom
              gas: "200000"
            memo: memo
            signatures:
            - signature: signature
              pub_key: pub_key
            - signature: signature
              pub_key: pub_key
        from: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
        tradeId: 0
      properties:
        tradeId:
          description: generated by the API server
          example: 0
          format: int64
          minimum: 0
          type: integer
        from:
          example: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          type: string
        crossTx:
          $ref: '#/components/schemas/CrossTx'
      required:
      - crossTx
      - from
      - tradeId
      type: object
    Estate:
      example:
        dividendDate: 2020-11-01T00:00:00.000+0000
        offerPrice: 10000
        tokenId: 108000000000078c000000000000000000000000000000000000000000000839
        imagePath: /img/sample.jpg
        issuedBy: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
        name: Ginza Resort
        description: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
          commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et
          magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis,
          ultricies nec, pellentesque eu, pretium quis, sem.
        expectedYield: 500
      properties:
        tokenId:
          example: 108000000000078c000000000000000000000000000000000000000000000839
          maxLength: 64
          minLength: 64
          type: string
        name:
          example: Ginza Resort
          type: string
        imagePath:
          example: /img/sample.jpg
          type: string
        description:
          example: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus
            et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis,
            ultricies nec, pellentesque eu, pretium quis, sem.
          type: string
        offerPrice:
          description: public offering price
          example: 10000
          format: int64
          minimum: 0
          type: integer
        expectedYield:
          description: expected yield amount per share
          example: 500
          format: int64
          minimum: 0
          type: integer
        dividendDate:
          description: next dividend date
          example: 2020-11-01
          format: date
          type: string
        issuedBy:
          example: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          type: string
      required:
      - description
      - dividendDate
      - expectedYield
      - imagePath
      - issuedBy
      - name
      - offerPrice
      - tokenId
      type: object
    GetEstateOutput:
      description: for frontend's convenience
      example:
        estate:
          dividendDate: 2020-11-01T00:00:00.000+0000
          offerPrice: 10000
          tokenId: 108000000000078c000000000000000000000000000000000000000000000839
          imagePath: /img/sample.jpg
          issuedBy: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          name: Ginza Resort
          description: Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean
            commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus
            et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis,
            ultricies nec, pellentesque eu, pretium quis, sem.
          expectedYield: 500
        trades:
        - seller: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          canceled: true
          estateId: 108000000000078c000000000000000000000000000000000000000000000839
          price: 500
          id: 0
          requests:
          - canceled: true
            crossTx:
              type: cosmos-sdk/StdTx
              value:
                msg:
                - type: cross/MsgInitiate
                  value:
                    Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    Nonce: "0"
                    TimeoutHeight: "149"
                    ContractTransactions:
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    ChainID: ibc0
                - type: cross/MsgInitiate
                  value:
                    Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    Nonce: "0"
                    TimeoutHeight: "149"
                    ContractTransactions:
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    ChainID: ibc0
                fee:
                  amount:
                  - amount: 0
                    denom: denom
                  - amount: 0
                    denom: denom
                  gas: "200000"
                memo: memo
                signatures:
                - signature: signature
                  pub_key: pub_key
                - signature: signature
                  pub_key: pub_key
            from: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            id: 0
            tradeId: 0
            updatedAt: 2000-01-23T04:56:07.000+00:00
          - canceled: true
            crossTx:
              type: cosmos-sdk/StdTx
              value:
                msg:
                - type: cross/MsgInitiate
                  value:
                    Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    Nonce: "0"
                    TimeoutHeight: "149"
                    ContractTransactions:
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    ChainID: ibc0
                - type: cross/MsgInitiate
                  value:
                    Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    Nonce: "0"
                    TimeoutHeight: "149"
                    ContractTransactions:
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    ChainID: ibc0
                fee:
                  amount:
                  - amount: 0
                    denom: denom
                  - amount: 0
                    denom: denom
                  gas: "200000"
                memo: memo
                signatures:
                - signature: signature
                  pub_key: pub_key
                - signature: signature
                  pub_key: pub_key
            from: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            id: 0
            tradeId: 0
            updatedAt: 2000-01-23T04:56:07.000+00:00
          type: buy
          buyer: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          updatedAt: 2000-01-23T04:56:07.000+00:00
        - seller: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          canceled: true
          estateId: 108000000000078c000000000000000000000000000000000000000000000839
          price: 500
          id: 0
          requests:
          - canceled: true
            crossTx:
              type: cosmos-sdk/StdTx
              value:
                msg:
                - type: cross/MsgInitiate
                  value:
                    Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    Nonce: "0"
                    TimeoutHeight: "149"
                    ContractTransactions:
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    ChainID: ibc0
                - type: cross/MsgInitiate
                  value:
                    Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    Nonce: "0"
                    TimeoutHeight: "149"
                    ContractTransactions:
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    ChainID: ibc0
                fee:
                  amount:
                  - amount: 0
                    denom: denom
                  - amount: 0
                    denom: denom
                  gas: "200000"
                memo: memo
                signatures:
                - signature: signature
                  pub_key: pub_key
                - signature: signature
                  pub_key: pub_key
            from: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            id: 0
            tradeId: 0
            updatedAt: 2000-01-23T04:56:07.000+00:00
          - canceled: true
            crossTx:
              type: cosmos-sdk/StdTx
              value:
                msg:
                - type: cross/MsgInitiate
                  value:
                    Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    Nonce: "0"
                    TimeoutHeight: "149"
                    ContractTransactions:
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    ChainID: ibc0
                - type: cross/MsgInitiate
                  value:
                    Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                    Nonce: "0"
                    TimeoutHeight: "149"
                    ContractTransactions:
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    - signers:
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                      ops:
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      - type: store/lock/Write
                        value:
                          V: V
                          K: K
                      contract: contract
                      source:
                        port: cross
                        channel: ibcconexfer
                    ChainID: ibc0
                fee:
                  amount:
                  - amount: 0
                    denom: denom
                  - amount: 0
                    denom: denom
                  gas: "200000"
                memo: memo
                signatures:
                - signature: signature
                  pub_key: pub_key
                - signature: signature
                  pub_key: pub_key
            from: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            id: 0
            tradeId: 0
            updatedAt: 2000-01-23T04:56:07.000+00:00
          type: buy
          buyer: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          updatedAt: 2000-01-23T04:56:07.000+00:00
      properties:
        estate:
          $ref: '#/components/schemas/Estate'
        trades:
          items:
            $ref: '#/components/schemas/Trade'
          type: array
      required:
      - estate
      - trades
      type: object
    User:
      example:
        name: Alice
        mnemonic: bullet client worth sleep claw carpet gallery rent sketch media
          north panel disagree taxi ship
        id: alice
      properties:
        id:
          example: alice
          type: string
        name:
          example: Alice
          type: string
        mnemonic:
          example: bullet client worth sleep claw carpet gallery rent sketch media
            north panel disagree taxi ship
          type: string
      required:
      - id
      - mnemonic
      - name
      type: object
    AccAddress:
      example: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
      type: string
    CrossTx:
      example:
        type: cosmos-sdk/StdTx
        value:
          msg:
          - type: cross/MsgInitiate
            value:
              Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              Nonce: "0"
              TimeoutHeight: "149"
              ContractTransactions:
              - signers:
                - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                ops:
                - type: store/lock/Write
                  value:
                    V: V
                    K: K
                - type: store/lock/Write
                  value:
                    V: V
                    K: K
                contract: contract
                source:
                  port: cross
                  channel: ibcconexfer
              - signers:
                - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                ops:
                - type: store/lock/Write
                  value:
                    V: V
                    K: K
                - type: store/lock/Write
                  value:
                    V: V
                    K: K
                contract: contract
                source:
                  port: cross
                  channel: ibcconexfer
              ChainID: ibc0
          - type: cross/MsgInitiate
            value:
              Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              Nonce: "0"
              TimeoutHeight: "149"
              ContractTransactions:
              - signers:
                - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                ops:
                - type: store/lock/Write
                  value:
                    V: V
                    K: K
                - type: store/lock/Write
                  value:
                    V: V
                    K: K
                contract: contract
                source:
                  port: cross
                  channel: ibcconexfer
              - signers:
                - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
                ops:
                - type: store/lock/Write
                  value:
                    V: V
                    K: K
                - type: store/lock/Write
                  value:
                    V: V
                    K: K
                contract: contract
                source:
                  port: cross
                  channel: ibcconexfer
              ChainID: ibc0
          fee:
            amount:
            - amount: 0
              denom: denom
            - amount: 0
              denom: denom
            gas: "200000"
          memo: memo
          signatures:
          - signature: signature
            pub_key: pub_key
          - signature: signature
            pub_key: pub_key
      properties:
        type:
          example: cosmos-sdk/StdTx
          type: string
        value:
          $ref: '#/components/schemas/StdTx'
      required:
      - type
      - value
      type: object
    StdTx:
      description: same as cosmos sdk
      example:
        msg:
        - type: cross/MsgInitiate
          value:
            Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            Nonce: "0"
            TimeoutHeight: "149"
            ContractTransactions:
            - signers:
              - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              ops:
              - type: store/lock/Write
                value:
                  V: V
                  K: K
              - type: store/lock/Write
                value:
                  V: V
                  K: K
              contract: contract
              source:
                port: cross
                channel: ibcconexfer
            - signers:
              - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              ops:
              - type: store/lock/Write
                value:
                  V: V
                  K: K
              - type: store/lock/Write
                value:
                  V: V
                  K: K
              contract: contract
              source:
                port: cross
                channel: ibcconexfer
            ChainID: ibc0
        - type: cross/MsgInitiate
          value:
            Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            Nonce: "0"
            TimeoutHeight: "149"
            ContractTransactions:
            - signers:
              - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              ops:
              - type: store/lock/Write
                value:
                  V: V
                  K: K
              - type: store/lock/Write
                value:
                  V: V
                  K: K
              contract: contract
              source:
                port: cross
                channel: ibcconexfer
            - signers:
              - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
              ops:
              - type: store/lock/Write
                value:
                  V: V
                  K: K
              - type: store/lock/Write
                value:
                  V: V
                  K: K
              contract: contract
              source:
                port: cross
                channel: ibcconexfer
            ChainID: ibc0
        fee:
          amount:
          - amount: 0
            denom: denom
          - amount: 0
            denom: denom
          gas: "200000"
        memo: memo
        signatures:
        - signature: signature
          pub_key: pub_key
        - signature: signature
          pub_key: pub_key
      properties:
        msg:
          items:
            $ref: '#/components/schemas/Msg'
          type: array
        fee:
          $ref: '#/components/schemas/StdFee'
        signatures:
          items:
            $ref: '#/components/schemas/StdSignature'
          type: array
        memo:
          type: string
      required:
      - fee
      - memo
      - msg
      type: object
    Msg:
      description: for MsgInitiate
      example:
        type: cross/MsgInitiate
        value:
          Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          Nonce: "0"
          TimeoutHeight: "149"
          ContractTransactions:
          - signers:
            - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            ops:
            - type: store/lock/Write
              value:
                V: V
                K: K
            - type: store/lock/Write
              value:
                V: V
                K: K
            contract: contract
            source:
              port: cross
              channel: ibcconexfer
          - signers:
            - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
            ops:
            - type: store/lock/Write
              value:
                V: V
                K: K
            - type: store/lock/Write
              value:
                V: V
                K: K
            contract: contract
            source:
              port: cross
              channel: ibcconexfer
          ChainID: ibc0
      properties:
        type:
          example: cross/MsgInitiate
          type: string
        value:
          $ref: '#/components/schemas/MsgInitiate'
      required:
      - type
      - value
      type: object
    StdFee:
      example:
        amount:
        - amount: 0
          denom: denom
        - amount: 0
          denom: denom
        gas: "200000"
      properties:
        amount:
          items:
            $ref: '#/components/schemas/Coin'
          type: array
        gas:
          example: "200000"
          type: string
      required:
      - amount
      - gas
      type: object
    StdSignature:
      example:
        signature: signature
        pub_key: pub_key
      properties:
        pub_key:
          type: string
        signature:
          type: string
      required:
      - signature
      type: object
    Coin:
      example:
        amount: 0
        denom: denom
      properties:
        denom:
          type: string
        amount:
          format: int64
          type: integer
      required:
      - amount
      type: object
    MsgInitiate:
      description: a message type defined by cross
      example:
        Sender: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
        Nonce: "0"
        TimeoutHeight: "149"
        ContractTransactions:
        - signers:
          - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          ops:
          - type: store/lock/Write
            value:
              V: V
              K: K
          - type: store/lock/Write
            value:
              V: V
              K: K
          contract: contract
          source:
            port: cross
            channel: ibcconexfer
        - signers:
          - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          ops:
          - type: store/lock/Write
            value:
              V: V
              K: K
          - type: store/lock/Write
            value:
              V: V
              K: K
          contract: contract
          source:
            port: cross
            channel: ibcconexfer
        ChainID: ibc0
      properties:
        Sender:
          example: cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
          type: string
        ChainID:
          example: ibc0
          type: string
        ContractTransactions:
          items:
            $ref: '#/components/schemas/ContractTransaction'
          type: array
        TimeoutHeight:
          example: "149"
          type: string
        Nonce:
          example: "0"
          type: string
      required:
      - ChainID
      - ContractTransactions
      - Nonce
      - Sender
      - TimeoutHeight
      type: object
    ContractTransaction:
      example:
        signers:
        - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
        - cosmos14rvdh4uv8r02nj5dgxxstrahhktqxxj6xnwr0k
        ops:
        - type: store/lock/Write
          value:
            V: V
            K: K
        - type: store/lock/Write
          value:
            V: V
            K: K
        contract: contract
        source:
          port: cross
          channel: ibcconexfer
      properties:
        source:
          $ref: '#/components/schemas/ChannelInfo'
        signers:
          items:
            $ref: '#/components/schemas/AccAddress'
          type: array
        contract:
          format: byte
          type: string
        ops:
          items:
            $ref: '#/components/schemas/Op'
          type: array
      required:
      - contract
      - ops
      - signers
      - source
      type: object
    ChannelInfo:
      description: defined by cross
      example:
        port: cross
        channel: ibcconexfer
      properties:
        port:
          example: cross
          type: string
        channel:
          example: ibcconexfer
          type: string
      required:
      - channel
      - port
      type: object
    Op:
      example:
        type: store/lock/Write
        value:
          V: V
          K: K
      properties:
        type:
          example: store/lock/Write
          type: string
        value:
          $ref: '#/components/schemas/OpValue'
      required:
      - type
      - value
      type: object
    OpValue:
      description: Write(K, V) or Read(K)
      example:
        V: V
        K: K
      properties:
        K:
          format: byte
          type: string
        V:
          format: byte
          type: string
      required:
      - K
      type: object
